# bin2c.cmake — Convert a binary file to a C source with a byte array.
#
# Usage (from add_custom_command):
#   cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -DVAR_NAME=<identifier> -P bin2c.cmake
#
# Produces a .c file defining:
#   const unsigned char <VAR_NAME>[];
#   const size_t        <VAR_NAME>_size;

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "bin2c.cmake requires INPUT_FILE, OUTPUT_FILE and VAR_NAME")
endif()

file(READ "${INPUT_FILE}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# Format hex pairs as 0xNN comma-separated, 16 bytes per line.
set(c_array "")
set(i 0)
while(i LESS hex_len)
    string(SUBSTRING "${hex_content}" ${i} 2 byte)
    string(APPEND c_array "0x${byte},")
    math(EXPR i "${i} + 2")
    math(EXPR col "(${i} / 2) % 16")
    if(col EQUAL 0)
        string(APPEND c_array "\n    ")
    endif()
endwhile()

file(WRITE "${OUTPUT_FILE}"
"/* Generated by bin2c.cmake — do not edit. */\n"
"#include <stddef.h>\n"
"\n"
"const unsigned char ${VAR_NAME}[] = {\n"
"    ${c_array}\n"
"};\n"
"\n"
"const size_t ${VAR_NAME}_size = ${byte_count};\n"
)
